<?php include('header.php'); ?>
<div id="corps">
    <section class="full"><article>
    <h3>Conditions générales de vente</h3>
    <h4>Article 1 – Préambule</h4>
    <p>Champ d’application : ces conditions générales s’appliquent à toute commande de produits sur le site internet de la société SeBIO S.P.R.L. (ci-après dénommée SeBIO), enregistrée auprès du registre des personnes morales sous le numéro 0885.855.963 (TVA BE 885.855.963). Son siège social est situé à 1190 Bruxelles, au 101A rue du Monténégro.  Email : contact@sebio.be</p>
    <p>Toute commande d'un produit figurant au sein de la boutique en ligne du site www.sebio.be, suppose l'acceptation pleine et entière des présentes conditions générales.</p>
    <p>En conséquence, le client reconnaît être parfaitement informé du fait que son accord concernant le contenu des présentes conditions générales ne nécessite pas la signature manuscrite de ce document, dans la mesure où le client souhaite commander en ligne les produits présentés dans le cadre de la boutique du site web.</p>
    <h4>Article 2 - Conditions générales</h4>
    <h5>2.1. Généralités</h5>
    <p>Le client dispose de la faculté de sauvegarder ou d'éditer les présentes conditions générales, étant précisé que tant la sauvegarde que l'édition de ce document, relèvent de sa seule responsabilité.</p>
    <p>SeBIO pourra modifier les présentes conditions générales de vente à tout moment sous réserve de faire apparaître ces modifications sur son site. Néanmoins, les contrats en cours restent soumis aux conditions applicables au moment de la conclusion de la vente. Il vous est donc conseillé de vous référer régulièrement à la dernière version des conditions générales de ventes disponibles en permanence sur le site.</p>
    <h5>2.2. Définitions</h5>
    <p>Par CONSOMMATEUR, on entend toute personne physique ou juridique qui acquiert ou utilise, à des fins uniquement non professionnelles, des produits ou des services présentés sur le site web. En tant que consommateur, le client dispose donc de droits spécifiques, qui seraient remis en cause dans l'hypothèse où les produits ou services acquis dans le cadre du site web auraient en réalité un rapport avec son activité professionnelle.</p>
    <p>Par PROFESSIONNEL, on entend toute personne qui ne correspond pas à la définition du consommateur donnée ci-dessus.</p>
    <h4>Article 3 – Conclusions de la vente en ligne</h4>
    <p>Le catalogue de produits et leur description figurant sur www.sebio.be ne constitue pas une offre en tant que telle. Il ne suffit dès lors pas de remplir un formulaire de commande sur le site précité pour que le contrat de vente soit formé. La vente ne sera définitivement conclue que lors de la réception de l'email de confirmation.</p>
    <p>Pour la sécurité et la certitude du client, SeBIO se réserve le droit de lui demander des informations complémentaires et de refuser l'exécution de la commande à défaut de réponse adéquate ou si SeBIO estime que les informations en sa possession sont insuffisantes. SeBIO peut également refuser des commandes lorsqu'il apparaît que l'acheteur a l'intention de revendre les produits.</p>
    <h4>Article 4 – Confirmation de commande</h4>
    <p>Les informations contractuelles feront l'objet d'une confirmation par email au plus tard au moment de la livraison.</p>
    <h4>Article 5 – Achat</h4>
    <p>SeBIO répondra à votre commande dans la limite des stocks disponibles ou sous réserve des stocks disponibles chez ses fournisseurs. Les délais d'expédition sont donnés à titre indicatif. Néanmoins, si en dépit de sa vigilance les produits s'avéraient indisponibles après votre commande, SeBIO vous en informera par email et vous invitera à annuler ou modifier votre commande.</p>
    <h4>Article 6 – Disponibilité</h4>
    <p>La disponibilité des produits est toujours affichée sur notre site de manière indicative. En principe, un produit indiqué ‘en stock’ est disponible immédiatement. Cependant, SeBIO ne peut être tenue responsable si le stock n'est plus le même qu’à la date où la commande a été effectuée. Toute indisponibilité est en principe notée sur le site web.</p>
    <p>Si SeBIO ne peut obtenir un produit de la part de ses fournisseurs dans un délai raisonnable (par exemple en cas de rupture de stock chez le fournisseur lui-même), elle notifiera au client le retard prévu par courrier électronique. Ce dernier pourra alors choisir d'annuler ou d’échange sa commande, sur base de ces nouvelles informations. Aucune pénalité d'annulation ne sera appliquée pour une telle annulation de commande.</p>
    <p>SeBIO se réserve le droit d’envoyer la commande en deux ou plusieurs fois si un produit était indisponible. Cet envoi se fera sans aucun surcoût pour le client (ce dernier ne paiera qu’une fois les frais de livraison indiqués au moment de la commande).</p>
    <h4>Article 7 – Transfert de propriété</h4>
    <p>Par dérogation à l'article 1583 du Code civil, les biens vendus ou livrés demeurent la propriété exclusive de SeBIO jusqu'au paiement intégral de la commande.</p>
    <p>Les risques liés au transfert de propriété des produits diffèrent selon que le client opte pour l’envoi de sa commande par le biais d’un envoi non sécurisé (la poste) ou par le biais d’un envoi sécurisé.</p>
    <p>Si la commande est envoyée par la poste, tous les risques de perte et de dégâts relatifs aux biens concernés sont à la charge du client dès le moment de la commande. Les articles achetés voyagent donc aux risques et périls de l’acheteur.</p>
    <p>Si le client opte pour un envoi sécurisé, SeBIO supportera les frais de tout dommage (vol, dégâts, objets manquants) causé au produit et remboursera dans ce cas les frais de transport.</p>
    <h4>Article 8 – Prix</h4>
    <p>Les prix de nos produits sont indiqués en EURO toutes taxes comprises, hors frais de port. Les frais de livraison et d’expédition sont à la charge du client (sauf conditions spéciales indiquées sur le site). Ils sont affichés, tenant compte de l’information fournie par le client relative au lieu de livraison.</p>
    <p>SeBIO se réserve le droit de modifier ses prix à tout moment. SeBIO s’engage cependant à appliquer les prix en vigueur qui vous auront été indiqués au moment de votre commande.</p>
    <h4>Article 9 – Paiement</h4>
    <p>Le paiement de la totalité du prix doit être réalisé au moment de votre commande, sauf si vous venez chercher votre commande dans notre show-room situé au 101A rue du Monténégro, à 1190 Bruxelles. Dans ce cas vous pouvez également payer en espèces au moment du retrait. Vous pouvez venir retirer votre commande pendant nos heures d'ouverture.</p>
    <p>A aucun moment, les sommes versées ne pourront être considérées comme des arrhes ou acomptes. Toutes les commandes sont payables en EURO. Pour régler votre commande, vous disposez des moyens de paiement suivants : cartes de crédit, paiements via paypal (email), cash (uniquement en cas de retrait de la commande dans notre magasin) ou virement bancaire.</p>
    <p>Dans ce dernier cas, les produits sont réservés à l’attention du client durant 5 jours ouvrables à partir de la commande, en attendant le paiement. Une fois passé ce délai, nous pouvons décider d’annuler la commande.</p>
    <p>Dans le cas d’un retrait de la marchandise au magasin, les produits sont également réservés à l’attention du client durant 5 jours ouvrables à partir de la commande. Une fois passé ce délai, nous pouvons décider d’annuler la commande.</p>
    <p>Vous garantissez à SeBIO de disposer de toutes les autorisations nécessaires pour utiliser le mode de paiement choisi lors de l'enregistrement du bon de commande. SeBIO se réserve le droit de suspendre ou d'annuler toute commande et/ou livraison, quels que soient leur nature et niveau d'exécution, en cas de non-paiement (ou en cas d'incident de paiement) de toute somme qui serait due. La livraison de toute nouvelle commande pourra être suspendue en cas de retard de paiement d'une précédente commande et ce, nonobstant les dispositions des présentes. SeBIO se réserve le droit de demander une photocopie de votre carte d'identité et/ou justificatif bancaire pour tout paiement par carte bancaire.</p>
    <h4>Article 10 – Livraison</h4>
    <h5>10.1. - Généralités</h5>
    <p>Les produits achetés sur SeBIO ne sont livrés que dans les pays indiqués sur le site. Ils seront livrés à l’adresse indiquée sur le bon de commande. Les délais indiqués sur la fiche article sont des délais indicatifs et correspondent aux délais de traitement d’expédition auxquels s’ajoute le délai d’acheminement.</p>
    <p>eBIO ne pourra être tenue pour responsable des conséquences dues à un retard d'acheminement lié à la responsabilité de la poste. Il n'y aura pas de remboursement de la commande tant que celle-ci ne sera pas retournée à l 'expéditeur ou arrivée chez le destinataire avec retard.</p>
    <p>En cas de paiement par virement, la commande ne sera traitée qu’à la réception du montant. En conséquence, les délais applicables dans ce cas sont ceux au jour de réception du paiement et peuvent donc être modifiés par rapport à ceux mentionnés au jour de la passation de la commande.</p>
    <p>Si, vous décidez d’annuler votre commande après paiement et que votre commande est déjà partie pour livraison, SeBIO ne procédera au remboursement de ce produit, qu’à sa réception complète et à condition qu’il demeure dans son état d’origine. Les frais de transport et de renvoi sont à charge du client. (voir article 12, droit de renonciation)</p>
    <h5>10.2. – Transfert des risques</h5>
    <p>La propriété et les risques afférents à vos produits seront transférés lors de la réception des Produits.</p>
    <h5>10.3. - Droits de douane</h5>
    <p>Lorsque vous commandez des produits devant être livrés dans un pays autre que la Belgique, vous êtes considéré comme l’importateur agréé et devez à ce titre respecter les lois et réglementations en vigueur dans le pays dans lequel vous réceptionnez la marchandise.</p>
    <p>Vous pouvez être assujetti à des droits ou des taxes d’importation à l’arrivée de la marchandise dans votre pays. Tous les frais additionnels de dédouanement sont à votre charge. SeBIO n’a aucun contrôle sur ces frais et ne connaît pas leur montant. Les politiques douanières variant d’un pays à l’autre, vous devez contacter votre service des douanes locales pour de plus amples informations.</p>
    <h5>10.4 – Problèmes de livraison</h5>
    <p>Toute réserve sur le produit livré (par exemple : colis endommagé, déjà ouvert...) doit être notifiée à SeBIO dans les 3 jours suivant la réception du produit. En fonction des cas définis à l’article 7, vous pourrez éventuellement bénéficier ou non des conditions d'échange et de remboursement prévues à cet article.</p>
    <p>Tout problème concernant les articles contenus dans le colis (article périmé, manquant, ne correspondant pas à l'article commandé...) doit être notifié à SeBIO dans un délai de 7 jours suivant la réception du colis. Toute notification après ce délai n'engagera plus la responsabilité de SeBIO et ne sera donc ni remboursé ni remplacé.</p>
    <h5>10.5 - Conformité des produits</h5>
    <p>SeBIO s’engage à vous rembourser ou à vous échanger les produits apparemment défectueux de fabrique ou ne correspondant pas à votre commande. Dans ce cas, nous vous remercions de bien vouloir en faire état de manière détaillée par écrit et de renvoyer à SeBIO le ou les produits. SeBIO procédera, selon votre choix, à l'échange ou au remboursement du ou des produits. La demande doit être effectuée dans les sept jours ouvrables suivant la livraison. Toute réclamation formulée hors de ce délai ne pourra être acceptée.</p>
    <p>Les produits doivent être renvoyés à SeBIO dans l'état dans lequel vous les avez reçus avec l'ensemble des éléments livrés (accessoires, emballage, notice...). Les frais engendrés par ce renvoi vous seront remboursés sur la base du tarif facturé</p>
    <p>En tout état de cause, vous bénéficiez des dispositions de la garantie légale relatives à la garantie des vices cachés.</p>
    <p>Les dispositions de cet article ne vous empêchent pas de bénéficier du droit de renonciation (satisfait ou remboursé) prévu à l’article 12.</p>
    <h5>10.6 - Retour de colis</h5>
    <p>IMPORTANT: si le client n'est pas présent lors de la livraison et ne retire pas son colis auprès de la poste dans les 15 jours, le colis est retourné à SeBIO. Dans ce cas, SeBIO renverra le colis au client uniquement lorsque ce colis aura été reçu en retour (ou remboursé par la poste en cas de perte), et les frais de port de ce deuxième envoi seront demandés au client, et ceci même s'il s'avère que la poste n'a pas laissé d'avis de passage.</p>
    <h4>Article 11 – Garantie</h4>
    <p>11.1 Les produits achetés sur le présent site sont garantis par le fabricant conformément aux clauses et conditions spécifiques énoncées dans la documentation originale sur le produit.</p>
    <p>11.2 Lisez votre documentation sur le produit pour de plus amples informations sur la garantie du fabricant, qui ne remet pas en cause les droits impératifs prévus par la législation en vigueur.</p>
    <p>11.3 Toute demande de garantie doit, le cas échéant, être effectuée soit directement auprès du fabricant ou éditeur conformément aux dispositions de toute garantie annexée aux produits achetés, soit auprès de SeBIO par téléphone (auquel cas SeBIO s’efforcera de remédier à la situation pour votre compte).</p>
    <h4>Article 12 – Droit de renonciation</h4>
    <p>Conformément à la loi du 14 juillet 1991, le consommateur a le droit de notifier au vendeur qu'il renonce à l'achat, sans pénalités et sans indication de motif, dans les 7 jours ouvrables à dater du lendemain du jour de la livraison du produit. Attention: LES PRODUITS EN SOLDES FONT EXCEPTION A CETTE LOI, par conséquent ils ne seront jamais repris ni échangés !</p>
    <p>Les produits doivent impérativement être retournés à SeBIO dans un parfait état de revente, dans leur état d'origine (emballage, accessoires, notice), dûment scellés, ainsi qu’une copie de la facture ou du bon de livraison endéans les 10 jours.</p>
    <p>Tout produit incomplet, abîmé, endommagé ou dont l'emballage d'origine aura été détérioré, ne sera ni remboursé ni échangé.</p>
    <p>Le consommateur qui souhaite exercer ce droit, doit contacter SeBIO dans les 7 jours ouvrables à contact@sebio.be</p>
    <p>Les frais d'envoi que SeBIO aura engendré pour votre commande ne seront en aucun cas remboursés.</p>
    <p>Dans les 30 jours après l'acceptation de la reprise, SeBIO remboursera les sommes payées, déduction faite des frais de livraison qui sont à charge du consommateur.</p>
    <h4>Article 13 – Preuve de la transaction</h4>
    <p>Les registres informatisés, conservés dans les systèmes informatiques de SeBIO dans des conditions raisonnables de sécurité, seront considérés comme les preuves des communications, des commandes et des paiements intervenus entre les parties.</p>
    <p>L'archivage des bons de commande et des factures est effectué sur un support fiable et durable pouvant être produit à titre de preuve.</p>
    <h4>Article 14 – Limitation de responsabilité</h4>
    <p>14.1 Les photos et textes illustrant et décrivant les produits qui figurent sur le présent site sont non contractuels et uniquement à titre d’information. SeBIO n’assume aucune responsabilité en cas d’erreurs ou d’omissions dans les photos ou textes figurant sur le présent site. En outre, concernant les fiches techniques et les descriptions des produits provenant de nos partenaires ou fournisseurs, SeBIO décline toute responsabilité quant à la validité de leur contenu.</p>
    <p>14.2 Sans limiter la portée des présentes conditions générales de vente, aucune demande quelle qu’elle soit visant des produits livrés, la non livraison de produits ou autre ne peut dépasser le montant du prix d’achat des produits qui ont donné lieu à une demande de dommages et intérêts. En aucun cas SeBIO ne pourra être tenue pour responsable de dommages indirects, fortuits ou consécutifs de quelque nature que ce soit (même si la naissance d’un tel dommage était connue ou aurait pu l’être par SeBIO) survenant en rapport avec ses produits, leur utilisation, leur vente ou le site web.</p>
    <h4>Article 15 – Force majeure</h4>
    <p>15.1 SeBIO fera tout son possible pour s’acquitter de ses obligations mais ne pourra pas être tenue pour responsable de retards ou de l’absence de livraison découlant de circonstances indépendantes de sa volonté, comme des grèves, guerres, catastrophes naturelles ou autres qui empêchent la production, le transport ou la livraison de produits.</p>
    <p>15.2 En cas de retard, SeBIO s’acquittera de ses obligations dans les plus brefs délais et se réserve le droit de répartir les stocks de produits restants entre ses clients de manière équitable.</p>
    <h4>Article 16 – Protection des données</h4>
    <p>En passant votre Commande, vous donnez votre accord pour que SeBIO stocke, traite et utilise les données collectées à partir de votre bon de commande. Certaines de ces informations pourront être transférées aux sociétés qui interviennent pour la livraison de vos produits. En passant votre commande et si vous l’indiquez sur votre bon de commande, vous donnez également votre accord pour que SeBIO transfère de telles données à d'autres sociétés dont les produits sont disponibles à la vente sur le site internet de SeBIO, afin de vous fournir des informations concernant d'autres produits et services qui sont susceptibles de vous intéresser.</p>
    <p>Pour vous opposer au transfert de telles données à ces sociétés, ayant pour objet de vous informer sur les autres produits et services de SeBIO ou de tiers, vous devez indiquer votre refus dans la section appropriée du bon de commande. Vous pouvez obtenir une copie des données détenues par nous vous concernant en nous faisant parvenir une demande écrite. Si l'une des données détenue par nous vous concernant est incorrecte, elle sera corrigée sur demande écrite de votre part.</p>
    <h4>Article 17 – Droit applicable et for</h4>
    <p>SeBIO fera de son mieux pour essayer de régler à l’amiable tout différend. Si vous n’êtes pas satisfait par le mode de règlement du différend et que vous souhaitez faire appel aux tribunaux compétents, les règles suivantes s’appliqueront.</p>
    <p>Le contrat est régi par la loi belge. Chaque partie donne compétence exclusive pour que tout litige soit soumis à la compétence des tribunaux de Bruxelles (Belgique).</p>
        </article>
</section>
<?php include('footer.php'); ?>